name: SLUS_014.09
sha1: 0aaf76649164f1191f3f4e1a1c195f36bcb26b60
options:
  basename: slus_014.09
  target_path: EXTRACTED/SLUS_014.09
  elf_path: build/slus_014.09.elf
  base_path: ..
  platform: psx
  compiler: PSYQ

  asm_path: asm/SLUS_014.09
  src_path: src/SLUS_014.09
  build_path: build
  create_asm_dependencies: True

  ld_script_path: build/SLUS_014.09.ld
  ld_dependencies: True

  find_file_boundaries: False
  gp_value: 0x8009FC48
  # ld_gp_expression: main_SCOMMON_START + 0x7FF0

  o_as_suffix: False
  use_legacy_include_asm: False

  section_order: [".rodata", ".text", ".data", ".bss"]
  # auto_link_sections: [".data", ".rodata", ".bss"]

  symbol_addrs_path:
    - config/symbols.SLUS_014.09.txt
  reloc_addrs_path:
    - reloc_addrs.txt

  undefined_funcs_auto_path: config/undefined_funcs_auto.SLUS_014.09.txt
  undefined_syms_auto_path: config/undefined_syms_auto.SLUS_014.09.txt

  extensions_path: tools/splat_ext

  subalign: 2

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  # Uncomment this line if you need to use the maspsx reorder workaround hack
  # https://github.com/mkst/maspsx?tab=readme-ov-file#include_asm-reordering-workaround-hack
  # include_asm_macro_style: maspsx_hack
segments:
  - name: header
    type: header
    start: 0x0

  # 3 C functions at the top prior to the normal rodata/C/data setup
  # needs to be its own segment to avoid lumping into the same .text ordering
  - name: baby
    type: code
    start: 0x800
    vram: 0x80010000
    # bss_size: Please fill out this value when you figure out the bss size
    subsegments:
      - [0x800, c, 800]
  - [0x960]

  - name: main
    type: code
    start: 0x960
    vram: 0x80010160
    align: 4
    # bss_size: Please fill out this value when you figure out the bss size
    subsegments:
      - [0x960, .rodata, 5D3C]
      - [0x5D3C, c, 5D3C]
      - [0x63E00, data, 63E00] # this is more code but splat is being weird
      - [0x708C4, data, 708C4]
  - [0x91000]
